[package]
name = "telemetrix"
version = "0.1.0"
authors = ["Luke Nimtz <luke.nimtz@gmail.com>"]
edition = "2018"

[[bin]]
name = "telemetrix"

[dependencies]
libc = "0.1.12"
usb = "0.2.2"
unbounded-gpsd = "0.4.3"
