[package]
name = "telemetrix"
version = "0.1.0"
authors = ["Luke Nimtz <luke.nimtz@gmail.com>"]
edition = "2018"

[[bin]]
name = "telemetrix"

[dependencies]
udev = "0.2"
unbounded-gpsd = "0.4.3"
tokio = "0.1"
