name: telemetrix
version: git
summary: Telemetry and battery monitoring
description: |
  Work in progress

grade: devel

confinement: devmode
base: core18

architectures:
  - build-on: armhf
    run-on: armhf

parts:
  telemetrix:
    plugin: rust
    source: .
    build-packages:
      - libudev-dev
    stage-packages:
      - gpsd

apps:
  telemetrix:
    command: telemetrix

  gpsdctl:
    command: gpsdctl

  gpsd:
    daemon: simple
    command: gpsd -N -F /var/run/gpsd.sock
    plugs:
      - network-bind
